apiVersion: mongodb.com/v1
kind: MongoDBUser
metadata:
  name: root-k8-user
spec:
  username: CN=root-k8-user,OU=k8sdemo-agents,O=MongoDB,L=Sydney,ST=NSW,C=AU
  db: "$external"
  mongodbResourceRef:
    name: my-replica-set
  roles:
    - db: admin
      name: root